import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:simple_icons/simple_icons.dart' as si;

/// Shared registry of icon names to IconData for the designer.
/// Used both for the inspector icon picker and for rendering icons on the canvas.
/// Includes both LucideIcons (general-purpose) and SimpleIcons (brand/auto logos).
const Map<String, IconData> kDesignerIcons = {
  // ── Lucide Icons (general purpose) ────────────────────────────────
  'zap': LucideIcons.zap,
  'zap-off': LucideIcons.zapOff,
  'sun': LucideIcons.sun,
  'moon': LucideIcons.moon,
  'power': LucideIcons.power,
  'radio': LucideIcons.radio,
  'cpu': LucideIcons.cpu,
  'battery': LucideIcons.battery,
  'battery-charging': LucideIcons.batteryCharging,
  'thermometer': LucideIcons.thermometer,
  'gauge': LucideIcons.gauge,
  'activity': LucideIcons.activity,
  'check': LucideIcons.check,
  'circle-check': LucideIcons.circleCheck,
  'x': LucideIcons.x,
  'lock': LucideIcons.lock,
  'lock-open': LucideIcons.lockOpen,
  'lightbulb': LucideIcons.lightbulb,
  'fan': LucideIcons.fan,
  'mic': LucideIcons.mic,
  'speaker': LucideIcons.speaker,
  'volume-2': LucideIcons.volume2,
  'volume': LucideIcons.volume,
  'wifi': LucideIcons.wifi,
  'bluetooth': LucideIcons.bluetooth,
  'usb': LucideIcons.usb,
  'settings': LucideIcons.settings,
  'cog': LucideIcons.cog,
  'wrench': LucideIcons.wrench,
  'hammer': LucideIcons.hammer,
  'save': LucideIcons.save,
  'upload': LucideIcons.upload,
  'download': LucideIcons.download,
  'bell': LucideIcons.bell,
  'search': LucideIcons.search,
  'home': LucideIcons.house,
  'flag': LucideIcons.flag,
  'trash-2': LucideIcons.trash2,
  'play': LucideIcons.play,
  'pause': LucideIcons.pause,
  'stop-circle': LucideIcons.circleStop,
  'rewind': LucideIcons.rewind,
  'fast-forward': LucideIcons.fastForward,
  'music': LucideIcons.music,
  'camera': LucideIcons.camera,
  'video': LucideIcons.video,
  'monitor': LucideIcons.monitor,
  'smartphone': LucideIcons.smartphone,
  'tablet': LucideIcons.tablet,
  'gamepad-2': LucideIcons.gamepad2,
  'headphones': LucideIcons.headphones,
  'shield': LucideIcons.shield,
  'alert-triangle': LucideIcons.triangleAlert,
  'info': LucideIcons.info,
  'help-circle': LucideIcons.circleQuestionMark,
  'plus-circle': LucideIcons.circlePlus,
  'minus-circle': LucideIcons.circleMinus,
  'arrow-up': LucideIcons.arrowUp,
  'arrow-down': LucideIcons.arrowDown,
  'arrow-left': LucideIcons.arrowLeft,
  'arrow-right': LucideIcons.arrowRight,
  'chevron-up': LucideIcons.chevronUp,
  'chevron-down': LucideIcons.chevronDown,
  'maximize-2': LucideIcons.maximize2,
  'minimize-2': LucideIcons.minimize2,
  'rotate-ccw': LucideIcons.rotateCcw,
  'rotate-cw': LucideIcons.rotateCw,
  'refresh-ccw': LucideIcons.refreshCcw,
  'target': LucideIcons.target,
  'crosshair': LucideIcons.crosshair,
  'compass': LucideIcons.compass,
  'map-pin': LucideIcons.mapPin,
  'navigation': LucideIcons.navigation,
  'navigation-2': LucideIcons.navigation2,
  'wind': LucideIcons.wind,
  'droplets': LucideIcons.droplets,
  'snowflake': LucideIcons.snowflake,
  'flame': LucideIcons.flame,

  // ── SimpleIcons — Auto Brands ─────────────────────────────────────
  'acura': si.SimpleIcons.acura,
  'amg': si.SimpleIcons.amg,
  'astonmartin': si.SimpleIcons.astonmartin,
  'audi': si.SimpleIcons.audi,
  'bentley': si.SimpleIcons.bentley,
  'bmw': si.SimpleIcons.bmw,
  'bugatti': si.SimpleIcons.bugatti,
  'cadillac': si.SimpleIcons.cadillac,
  'chevrolet': si.SimpleIcons.chevrolet,
  'chrysler': si.SimpleIcons.chrysler,
  'citroen': si.SimpleIcons.citroen,
  'dacia': si.SimpleIcons.dacia,
  'dsautomobiles': si.SimpleIcons.dsautomobiles,
  'ducati': si.SimpleIcons.ducati,
  'ferrari': si.SimpleIcons.ferrari,
  'fiat': si.SimpleIcons.fiat,
  'ford': si.SimpleIcons.ford,
  'honda': si.SimpleIcons.honda,
  'hyundai': si.SimpleIcons.hyundai,
  'infiniti': si.SimpleIcons.infiniti,
  'jeep': si.SimpleIcons.jeep,
  'kia': si.SimpleIcons.kia,
  'koenigsegg': si.SimpleIcons.koenigsegg,
  'ktm': si.SimpleIcons.ktm,
  'lada': si.SimpleIcons.lada,
  'lamborghini': si.SimpleIcons.lamborghini,
  'mahindra': si.SimpleIcons.mahindra,
  'maserati': si.SimpleIcons.maserati,
  'mazda': si.SimpleIcons.mazda,
  'mclaren': si.SimpleIcons.mclaren,
  'mg': si.SimpleIcons.mg,
  'mini': si.SimpleIcons.mini,
  'mitsubishi': si.SimpleIcons.mitsubishi,
  'nissan': si.SimpleIcons.nissan,
  'opel': si.SimpleIcons.opel,
  'peugeot': si.SimpleIcons.peugeot,
  'polestar': si.SimpleIcons.polestar,
  'porsche': si.SimpleIcons.porsche,
  'ram': si.SimpleIcons.ram,
  'renault': si.SimpleIcons.renault,
  'rimacautomobili': si.SimpleIcons.rimacautomobili,
  'rollsroyce': si.SimpleIcons.rollsroyce,
  'scania': si.SimpleIcons.scania,
  'seat': si.SimpleIcons.seat,
  'skoda': si.SimpleIcons.skoda,
  'smart': si.SimpleIcons.smart,
  'subaru': si.SimpleIcons.subaru,
  'suzuki': si.SimpleIcons.suzuki,
  'tata': si.SimpleIcons.tata,
  'tesla': si.SimpleIcons.tesla,
  'toyota': si.SimpleIcons.toyota,
  'vauxhall': si.SimpleIcons.vauxhall,
  'volkswagen': si.SimpleIcons.volkswagen,
  'volvo': si.SimpleIcons.volvo,

  // ── SimpleIcons — Automotive / Related Brands ─────────────────────
  'aral': si.SimpleIcons.aral,
  'autozone': si.SimpleIcons.autozone,
  'bosch': si.SimpleIcons.bosch,
  'carthrottle': si.SimpleIcons.carthrottle,
  'caterpillar': si.SimpleIcons.caterpillar,
  'daf': si.SimpleIcons.daf,
  'generalmotors': si.SimpleIcons.generalmotors,
  'iveco': si.SimpleIcons.iveco,
  'johndeere': si.SimpleIcons.johndeere,
  'man': si.SimpleIcons.man,
  'onstar': si.SimpleIcons.onstar,
  'oshkosh': si.SimpleIcons.oshkosh,
};

/// Resolve an icon name string to IconData, or null if unknown.
IconData? iconFromName(String? name) {
  if (name == null) return null;
  return kDesignerIcons[name];
}
