/**
 * BasicSwitch — RadioKit Example
 *
 * Demonstrates the simplest RadioKit USB Serial setup:
 *   - A rocker switch controls the built-in RGB LED (WS2812)
 *   - All widgets are declared in RADIOKIT.h (generated by the designer)
 *
 * Hardware:
 *   - lolin_s3_mini (ESP32-S3) with WS2812 RGB LED on GPIO 2
 *   - No external components needed
 *
 * Usage:
 *   1. Flash to ESP32
 *   2. Open the RadioKit app and connect via USB Serial at 1000000 baud
 *   3. Tap the switch to toggle the LED
 */

#include <Arduino.h>
#include "RADIOKIT.h"

// ── Pin definitions ───────────────────────────────────────────
#define LED_PIN       2  // This is a regular LED, not a neopixel!!!
#define BUTTON_PIN   14

// ────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(1000000);
  while (!Serial) { delay(10); } // Wait for host to open port (DTR/RTS)
  delay(500); // Brief settle time after DTR received
  Serial.println("--- RadioKit BasicSwitch Start ---");

  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  led_1.rk.state = false;
  led_2.rk.state = false;

  // Initialize RadioKit from the UI config and start USB Serial.
  initRadioKit();

  Serial.println("RK: Setup complete.");
}

// ── State tracking ────────────────────────────────────────────
static bool lastSwitchState = false;

// ────────────────────────────────────────────────────────────
void loop() {
  // Always call update() to process incoming packets and manage connections.
  RadioKit.update();

  // Sync the physical LED only when the switch state changes.
  bool switchNow = slide_switch_1.rk.state;
  if (switchNow != lastSwitchState) {
    lastSwitchState = switchNow;
    digitalWrite(LED_PIN, switchNow ? HIGH : LOW);
  }

  // button_1 → led_1 (direct mapping)
  led_1.rk.state = button_1.rk.state;

  // Physical button on BUTTON_PIN → led_2 (direct mapping)
  bool btnPressed = (digitalRead(BUTTON_PIN) == LOW);
  led_2.rk.state = btnPressed;
}

