import 'package:flutter/widgets.dart';
import 'package:phosphoricons_flutter/phosphoricons_flutter.dart';
import 'package:simple_icons/simple_icons.dart' as si;

/// Shared registry of icon names to IconData for the designer.
/// Used both for the inspector icon picker and for rendering icons on the canvas.
/// Includes PhosphorIconsFill (fill-weight glyphs) and SimpleIcons (brand/auto logos).
const Map<String, IconData> kDesignerIcons = {
  // ── Phosphor — Fill (general purpose) ─────────────────────────────
  'zap': PhosphorIconsFill.lightning,
  'zap-off': PhosphorIconsFill.lightningSlash,
  'sun': PhosphorIconsFill.sun,
  'moon': PhosphorIconsFill.moon,
  'power': PhosphorIconsFill.power,
  'radio': PhosphorIconsFill.radio,
  'cpu': PhosphorIconsFill.cpu,
  'battery': PhosphorIconsFill.batteryFull,
  'battery-charging': PhosphorIconsFill.batteryCharging,
  'thermometer': PhosphorIconsFill.thermometer,
  'gauge': PhosphorIconsFill.gauge,
  'activity': PhosphorIconsFill.activity,
  'check': PhosphorIconsFill.check,
  'circle-check': PhosphorIconsFill.checkCircle,
  'x': PhosphorIconsFill.x,
  'lock': PhosphorIconsFill.lock,
  'lock-open': PhosphorIconsFill.lockOpen,
  'lightbulb': PhosphorIconsFill.lightbulb,
  'fan': PhosphorIconsFill.fan,
  'mic': PhosphorIconsFill.microphone,
  'speaker': PhosphorIconsFill.speakerHigh,
  'volume-2': PhosphorIconsFill.speakerHigh,
  'volume': PhosphorIconsFill.speakerLow,
  'wifi': PhosphorIconsFill.wifiHigh,
  'bluetooth': PhosphorIconsFill.bluetooth,
  'usb': PhosphorIconsFill.usb,
  'settings': PhosphorIconsFill.gearSix,
  'cog': PhosphorIconsFill.gear,
  'wrench': PhosphorIconsFill.wrench,
  'hammer': PhosphorIconsFill.hammer,
  'save': PhosphorIconsFill.floppyDisk,
  'upload': PhosphorIconsFill.upload,
  'download': PhosphorIconsFill.download,
  'search': PhosphorIconsFill.magnifyingGlass,
  'home': PhosphorIconsFill.house,
  'flag': PhosphorIconsFill.flag,
  'trash-2': PhosphorIconsFill.trash,
  'play': PhosphorIconsFill.play,
  'pause': PhosphorIconsFill.pause,
  'stop-circle': PhosphorIconsFill.stopCircle,
  'music': PhosphorIconsFill.musicNote,
  'camera': PhosphorIconsFill.camera,
  'video': PhosphorIconsFill.videoCamera,
  'monitor': PhosphorIconsFill.monitor,
  'smartphone': PhosphorIconsFill.deviceMobile,
  'tablet': PhosphorIconsFill.deviceTablet,
  'gamepad-2': PhosphorIconsFill.gameController,
  'headphones': PhosphorIconsFill.headphones,
  'shield': PhosphorIconsFill.shield,
  'alert-triangle': PhosphorIconsFill.warning,
  'info': PhosphorIconsFill.info,
  'help-circle': PhosphorIconsFill.question,
  'plus-circle': PhosphorIconsFill.plusCircle,
  'minus-circle': PhosphorIconsFill.minusCircle,
  'arrow-up': PhosphorIconsFill.arrowUp,
  'arrow-down': PhosphorIconsFill.arrowDown,
  'arrow-left': PhosphorIconsFill.arrowLeft,
  'arrow-right': PhosphorIconsFill.arrowRight,
  'chevron-up': PhosphorIconsFill.caretUp,
  'chevron-down': PhosphorIconsFill.caretDown,
  'maximize-2': PhosphorIconsFill.arrowsOut,
  'minimize-2': PhosphorIconsFill.arrowsIn,
  'rotate-ccw': PhosphorIconsFill.arrowCounterClockwise,
  'rotate-cw': PhosphorIconsFill.arrowClockwise,
  'refresh-ccw': PhosphorIconsFill.arrowsCounterClockwise,
  'target': PhosphorIconsFill.target,
  'crosshair': PhosphorIconsFill.crosshair,
  'compass': PhosphorIconsFill.compass,
  'map-pin': PhosphorIconsFill.mapPin,
  'navigation': PhosphorIconsFill.navigationArrow,
  'navigation-2': PhosphorIconsFill.navigationArrow,
  'wind': PhosphorIconsFill.wind,
  'droplets': PhosphorIconsFill.drop,
  'snowflake': PhosphorIconsFill.snowflake,
  'flame': PhosphorIconsFill.flame,

  // ── Phosphor — Fill (widget set) ─────────────────────────────────
  'caret-left': PhosphorIconsFill.caretLeft,
  'caret-right': PhosphorIconsFill.caretRight,
  'siren': PhosphorIconsFill.siren,
  'headlights': PhosphorIconsFill.headlights,
  'arrow-fat-left': PhosphorIconsFill.arrowFatLeft,
  'arrow-fat-right': PhosphorIconsFill.arrowFatRight,
  'warning': PhosphorIconsFill.warning,
  'fallout-shelter': PhosphorIconsFill.falloutShelter,
  'biohazard': PhosphorIconsFill.biohazard,
  'radioactive': PhosphorIconsFill.radioactive,
  'lightbulb-filament': PhosphorIconsFill.lightbulbFilament,
  'lighthouse': PhosphorIconsFill.lighthouse,
  'lightning': PhosphorIconsFill.lightning,
  'fire': PhosphorIconsFill.fire,
  'subway': PhosphorIconsFill.subway,
  'cable-car': PhosphorIconsFill.cableCar,
  'ghost': PhosphorIconsFill.ghost,
  'car-simple': PhosphorIconsFill.carSimple,
  'megaphone': PhosphorIconsFill.megaphone,
  'steering-wheel': PhosphorIconsFill.steeringWheel,
  'rewind': PhosphorIconsFill.rewind,
  'fast-forward': PhosphorIconsFill.fastForward,
  'bell': PhosphorIconsFill.bell,
  'bell-ringing': PhosphorIconsFill.bellRinging,
  'cat': PhosphorIconsFill.cat,
  'charging-station': PhosphorIconsFill.chargingStation,

  // ── SimpleIcons — Auto Brands ─────────────────────────────────────
  'acura': si.SimpleIcons.acura,
  'amg': si.SimpleIcons.amg,
  'astonmartin': si.SimpleIcons.astonmartin,
  'audi': si.SimpleIcons.audi,
  'bentley': si.SimpleIcons.bentley,
  'bmw': si.SimpleIcons.bmw,
  'bugatti': si.SimpleIcons.bugatti,
  'cadillac': si.SimpleIcons.cadillac,
  'chevrolet': si.SimpleIcons.chevrolet,
  'chrysler': si.SimpleIcons.chrysler,
  'citroen': si.SimpleIcons.citroen,
  'dacia': si.SimpleIcons.dacia,
  'dsautomobiles': si.SimpleIcons.dsautomobiles,
  'ducati': si.SimpleIcons.ducati,
  'ferrari': si.SimpleIcons.ferrari,
  'fiat': si.SimpleIcons.fiat,
  'ford': si.SimpleIcons.ford,
  'honda': si.SimpleIcons.honda,
  'hyundai': si.SimpleIcons.hyundai,
  'infiniti': si.SimpleIcons.infiniti,
  'jeep': si.SimpleIcons.jeep,
  'kia': si.SimpleIcons.kia,
  'koenigsegg': si.SimpleIcons.koenigsegg,
  'ktm': si.SimpleIcons.ktm,
  'lada': si.SimpleIcons.lada,
  'lamborghini': si.SimpleIcons.lamborghini,
  'mahindra': si.SimpleIcons.mahindra,
  'maserati': si.SimpleIcons.maserati,
  'mazda': si.SimpleIcons.mazda,
  'mclaren': si.SimpleIcons.mclaren,
  'mg': si.SimpleIcons.mg,
  'mini': si.SimpleIcons.mini,
  'mitsubishi': si.SimpleIcons.mitsubishi,
  'nissan': si.SimpleIcons.nissan,
  'opel': si.SimpleIcons.opel,
  'peugeot': si.SimpleIcons.peugeot,
  'polestar': si.SimpleIcons.polestar,
  'porsche': si.SimpleIcons.porsche,
  'ram': si.SimpleIcons.ram,
  'renault': si.SimpleIcons.renault,
  'rimacautomobili': si.SimpleIcons.rimacautomobili,
  'rollsroyce': si.SimpleIcons.rollsroyce,
  'scania': si.SimpleIcons.scania,
  'seat': si.SimpleIcons.seat,
  'skoda': si.SimpleIcons.skoda,
  'smart': si.SimpleIcons.smart,
  'subaru': si.SimpleIcons.subaru,
  'suzuki': si.SimpleIcons.suzuki,
  'tata': si.SimpleIcons.tata,
  'tesla': si.SimpleIcons.tesla,
  'toyota': si.SimpleIcons.toyota,
  'vauxhall': si.SimpleIcons.vauxhall,
  'volkswagen': si.SimpleIcons.volkswagen,
  'volvo': si.SimpleIcons.volvo,

  // ── SimpleIcons — Automotive / Related Brands ─────────────────────
  'aral': si.SimpleIcons.aral,
  'autozone': si.SimpleIcons.autozone,
  'bosch': si.SimpleIcons.bosch,
  'carthrottle': si.SimpleIcons.carthrottle,
  'caterpillar': si.SimpleIcons.caterpillar,
  'daf': si.SimpleIcons.daf,
  'generalmotors': si.SimpleIcons.generalmotors,
  'iveco': si.SimpleIcons.iveco,
  'johndeere': si.SimpleIcons.johndeere,
  'man': si.SimpleIcons.man,
  'onstar': si.SimpleIcons.onstar,
  'oshkosh': si.SimpleIcons.oshkosh,

};

/// Resolve an icon name string to IconData, or null if unknown.
IconData? iconFromName(String? name) {
  if (name == null) return null;
  return kDesignerIcons[name];
}
