/**
 * BasicSwitch — RadioKit Example
 *
 * Demonstrates the simplest RadioKit USB Serial setup:
 *   - A rocker switch controls the built-in RGB LED (WS2812)
 *   - All widgets are declared in RadioKit_UI.h (generated by the designer)
 *
 * Hardware:
 *   - lolin_s3_mini (ESP32-S3) with WS2812 RGB LED on GPIO 2
 *   - No external components needed
 *
 * Usage:
 *   1. Flash to ESP32
 *   2. Open the RadioKit app and connect via USB Serial at 1000000 baud
 *   3. Tap the switch to toggle the LED
 */

#include <Arduino.h>
#include "RadioKit_UI.h"

// ── Pin definitions ───────────────────────────────────────────
#define LED_PIN       2  // This is a regular LED, not a neopixel!!!
#define BUTTON_PIN   14

// ────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(1000000);
  delay(2000); // Give time for USB Serial to connect
  Serial.println("--- RadioKit BasicSwitch Start ---");

  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  led_1.off();
  led_2.off();

  // Initialize RadioKit from the UI config and start USB Serial.
  initRadioKit();

  Serial.println("RK: Setup complete.");
}

// ── State tracking ────────────────────────────────────────────
static bool lastSwitchState = false;

// ────────────────────────────────────────────────────────────
void loop() {
  // Always call update() to process incoming packets and manage connections.
  RadioKit.update();

  // Sync the physical LED only when the switch state changes.
  bool switchNow = slide_switch_1.get();
  if (switchNow != lastSwitchState) {
    lastSwitchState = switchNow;
    digitalWrite(LED_PIN, switchNow ? HIGH : LOW);
  }

  // button_1 → led_1 (direct mapping)
  if (button_1.get() != led_1.props.state) {
    led_1.set(button_1.get());
  }

  // Physical button on BUTTON_PIN → led_2 (direct mapping)
  bool btnPressed = (digitalRead(BUTTON_PIN) == LOW);
  if (btnPressed != led_2.props.state) {
    led_2.set(btnPressed);
  }
}

