[platformio]
default_envs = ble_rc_truck
src_dir = .

[env]
platform      = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework    = arduino
board         = lolin_s3_mini
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^2.1.0
    RadioKit=symlink://../..

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = dio

[env:ble_rc_truck]
